function New-GitIgnore {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$false)]
        [string[]]$Templates = @(),
        
        [Parameter(Mandatory=$false)]
        [string]$OutputPath = ".gitignore"
    )

    begin {
        Write-Verbose "Generating .gitignore file with templates: $($Templates -join ', ')"
    }

    process {
        try {
            $content = "# Generated by Clippy Developer Tools`n"
            $content += "# Generated on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`n"

            foreach ($template in $Templates) {
                $response = Invoke-RestMethod -Uri "https://raw.githubusercontent.com/github/gitignore/main/$template.gitignore"
                $content += "`n# Template for $template`n"
                $content += "$response`n"
            }

            $content | Out-File -FilePath $OutputPath -Encoding UTF8
            Write-Host "Created .gitignore file at $OutputPath"
        }
        catch {
            Write-Error "Failed to generate .gitignore file: $_"
        }
    }
}
